/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanegementsystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Simran-pc
 */
public class Signup3 extends javax.swing.JFrame {

    /**
     * Creates new form Signup3
     */
    String form;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu/MM/dd");
        LocalDate localDate = LocalDate.now();
        String date=dtf.format(localDate);
    public Signup3(String form) {
        initComponents();
        this.form=form;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cardno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        fd = new javax.swing.JRadioButton();
        saving = new javax.swing.JRadioButton();
        ca = new javax.swing.JRadioButton();
        ra = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        atm = new javax.swing.JCheckBox();
        mb = new javax.swing.JCheckBox();
        cb = new javax.swing.JCheckBox();
        ib = new javax.swing.JCheckBox();
        ea = new javax.swing.JCheckBox();
        es = new javax.swing.JCheckBox();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        R = new javax.swing.JCheckBox();
        cn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        trans = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        cardno.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setBackground(new java.awt.Color(108, 122, 137));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACCOUNT DETAILS");

        L1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setText("ACCOUNT TYPE  :");

        fd.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(fd);
        fd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fd.setForeground(new java.awt.Color(255, 255, 255));
        fd.setText("FIXED DEPOSITE");
        fd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdActionPerformed(evt);
            }
        });

        saving.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(saving);
        saving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saving.setForeground(new java.awt.Color(255, 255, 255));
        saving.setText("SAVING ");

        ca.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(ca);
        ca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ca.setForeground(new java.awt.Color(255, 255, 255));
        ca.setText("CURRENT");
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });

        ra.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(ra);
        ra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ra.setForeground(new java.awt.Color(255, 255, 255));
        ra.setText("RECURING DEPOSIT");
        ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account Number  :");

        jLabel3.setBackground(new java.awt.Color(44, 62, 80));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SERVICES REQUIRED  :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password  :");

        atm.setBackground(new java.awt.Color(44, 62, 80));
        atm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        atm.setForeground(new java.awt.Color(255, 255, 255));
        atm.setText("ATM CARD");

        mb.setBackground(new java.awt.Color(44, 62, 80));
        mb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mb.setForeground(new java.awt.Color(255, 255, 255));
        mb.setText("MOBILE BANKING");

        cb.setBackground(new java.awt.Color(44, 62, 80));
        cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(255, 255, 255));
        cb.setText("CHECKBOOK");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        ib.setBackground(new java.awt.Color(44, 62, 80));
        ib.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ib.setForeground(new java.awt.Color(255, 255, 255));
        ib.setText("INTERNET BANKING");

        ea.setBackground(new java.awt.Color(44, 62, 80));
        ea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ea.setForeground(new java.awt.Color(255, 255, 255));
        ea.setText("EMAIL ALERT");
        ea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaActionPerformed(evt);
            }
        });

        es.setBackground(new java.awt.Color(44, 62, 80));
        es.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        es.setForeground(new java.awt.Color(255, 255, 255));
        es.setText("E-STATEMENT");

        submit.setBackground(new java.awt.Color(0, 153, 0));
        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(204, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        R.setBackground(new java.awt.Color(44, 62, 80));
        R.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        R.setForeground(new java.awt.Color(255, 255, 255));
        R.setText("I HAVE DECLARED THAT ALL THE ABOVE STATEMENTS ARE CORRECT ");

        cn.setEditable(false);
        cn.setBackground(new java.awt.Color(108, 122, 137));
        cn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cn.setForeground(new java.awt.Color(255, 255, 255));
        cn.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Amt to be deposite  :");

        submit1.setBackground(new java.awt.Color(0, 153, 0));
        submit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit1.setText("Proceed");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        password.setEditable(false);
        password.setBackground(new java.awt.Color(108, 122, 137));
        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setCaretColor(new java.awt.Color(255, 255, 255));

        trans.setBackground(new java.awt.Color(108, 122, 137));
        trans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trans.setForeground(new java.awt.Color(255, 255, 255));
        trans.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cardnoLayout = new javax.swing.GroupLayout(cardno);
        cardno.setLayout(cardnoLayout);
        cardnoLayout.setHorizontalGroup(
            cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardnoLayout.createSequentialGroup()
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardnoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atm)
                            .addComponent(mb)
                            .addComponent(cb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardnoLayout.createSequentialGroup()
                                .addComponent(ib)
                                .addGap(17, 17, 17))
                            .addComponent(ea)
                            .addComponent(es)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardnoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardnoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(L1)
                            .addComponent(R)
                            .addGroup(cardnoLayout.createSequentialGroup()
                                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cardnoLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(41, 41, 41)
                                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca)
                    .addComponent(ra))
                .addGap(18, 18, 18)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saving)
                    .addComponent(fd))
                .addGap(69, 69, 69))
            .addGroup(cardnoLayout.createSequentialGroup()
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(submit))
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(submit1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardnoLayout.setVerticalGroup(
            cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardnoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardnoLayout.createSequentialGroup()
                        .addComponent(ca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ra)
                            .addComponent(saving)))
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addComponent(fd)
                        .addGap(29, 29, 29)))
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atm)
                    .addComponent(ib))
                .addGap(3, 3, 3)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mb)
                    .addComponent(ea))
                .addGap(3, 3, 3)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb)
                    .addComponent(es))
                .addGap(18, 18, 18)
                .addComponent(R)
                .addGap(18, 18, 18)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(submit))
                .addGap(18, 18, 18)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardnoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addGroup(cardnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(submit1))
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Step 3/3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(521, 521, 521))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void fdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdActionPerformed

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caActionPerformed

    private void raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String AcType = null;
        if(saving.isSelected()){ 
            AcType = "Saving Account";
        }
        else if(fd.isSelected()){ 
            AcType = "Fixed Deposit Account";
        }
        else if(ca.isSelected()){ 
            AcType = "Current Account";
        }else if(ra.isSelected()){ 
            AcType = "Recurring Deposit Account";
        }
        Random ran = new Random();
       // int first7 = (ran.nextInt(999999999)) ;
        //int start=1000000000;
        //long end = 9999999999L;
             //cardno = createRandomInteger(start,end,ran);
        //String cardno = "" + Math.abs(first7);
        long first4 = (ran.nextLong() % 9000000000L) + 9999999999L;
        String cardno = "" + Math.abs(first4);
        cn.setText(cardno);
        long first3 = (ran.nextLong() % 9000L) + 9999L;
        String passw = "" + Math.abs(first3);
        password.setText(passw);
        String facility = "";
        if(atm.isSelected()){ 
            facility = facility + " ATM Card";
        }
        if(ib.isSelected()){ 
            facility = facility + " Internet Banking";
        }
        if(mb.isSelected()){ 
            facility = facility + " Mobile Banking";
        }
        if(ea.isSelected()){ 
            facility = facility + " EMAIL Alerts";
        }
        if(cb.isSelected()){ 
            facility = facility + " Cheque Book";
        }
        if(es.isSelected()){ 
            facility = facility + " E-Statement";
        }
        
        //date 
        
        
        
        try{ 
            if(R.isSelected() )
            {
                conn c1 = new conn();
                String q1 = "Insert into signup3 values('"+form+"','"+AcType+"','"+cardno+"','"+passw+"','"+facility+"','"+date+"')";  
                c1.s.executeUpdate(q1);
                JOptionPane.showMessageDialog(null, "Account Number: " + cardno + "\n password:"+ passw+"\n Please note down your Account details");             
            }
            
            else{
                JOptionPane.showMessageDialog(null, "check all the requirements");
                }
            }
         catch (SQLException e)
            {
            JOptionPane.showMessageDialog(null,e);
            }
        
    }//GEN-LAST:event_submitActionPerformed

    private void eaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
         System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
        String Trans=trans.getText();
        String Accno=cn.getText();
        String name="";
        String ftrans="First Transaction";
        Random rand = new Random();
        int ran = rand.nextInt(999);
        try{ 
            if(!(Trans.equals("")))
            {
                conn c1 = new conn();
                String q="Select Name From signup Where formno IN(Select formno From signup3 where Accno='"+Accno+"')";
                ResultSet rs=c1.s.executeQuery(q);
                while(rs.next())
                {
                    name=rs.getString("Name");
                }
                String q1 = "Insert into passbook values('"+name+"','"+Accno+"','"+ftrans+"','0','"+Trans+"','"+Trans+"','"+date+"','"+ran+"')";
                c1.s.executeUpdate(q1);
                JOptionPane.showMessageDialog(null, Trans+" is Deposited to Your "+name+"'s Account\n ");       
                
                Transactions t1=new Transactions(Accno);
                t1.setVisible(true);
                this.dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(null, "check all the requirements");
                }
            }
         catch (SQLException e)
            {
            JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_submit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup3("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JCheckBox R;
    private javax.swing.JCheckBox atm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ca;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel cardno;
    private javax.swing.JCheckBox cb;
    private javax.swing.JTextField cn;
    private javax.swing.JCheckBox ea;
    private javax.swing.JCheckBox es;
    private javax.swing.JRadioButton fd;
    private javax.swing.JCheckBox ib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mb;
    private javax.swing.JTextField password;
    private javax.swing.JRadioButton ra;
    private javax.swing.JRadioButton saving;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JTextField trans;
    // End of variables declaration//GEN-END:variables

    private void createRandomInteger(int start, long end, Random ran) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
